# Generated by Django 5.2.6 on 2025-09-15 15:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('data_criacao', models.DateTimeField(verbose_name=datetime.datetime(2025, 9, 15, 15, 8, 11, 322465, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprest', models.DateField()),
                ('data_devol', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aberto,', 'Aberto'), ('Devolvido', 'Devolvido')], max_length=20)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb.liv+', to='proj_bib.usuario')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj_bib.usuario')),
            ],
        ),
    ]
